### ISSUE TITLE
Conda-forge about to update to GCC 10

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/gpuci-build-environment#214]
Conda-forge is about to move to GCC 10 for all of its non-CUDA package builds: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2010

This likely means we'll need to move to using GCC 10's libstdc++ in our build environment. Will need to replicate this (https://github.com/rapidsai/gpuci-build-environment/blob/branch-21.10/builds-gcc/Dockerfile.centos7-gcc7#L50-L54) into the GCC 9 images most likely.

**Comment by jakirkham** [comment]
cc @rapidsai/ops
