### ISSUE TITLE
Should build RHEL 7 gcc toolchains with `--disable-libstdcxx-dual-abi`

### ISSUE THREAD

**Issue by trxcllnt** [rapidsai/gpuci-build-environment#218]
[Dockerfile.centos7-gcc7](https://github.com/rapidsai/gpuci-build-environment/blob/branch-21.12/builds-gcc/Dockerfile.centos7-gcc7) and [Dockerfile.centos7-gcc9](https://github.com/rapidsai/gpuci-build-environment/blob/branch-21.12/builds-gcc/Dockerfile.centos7-gcc9) should pass the`--disable-libstdcxx-dual-abi` flag to use the [pre-C++-11 ABI](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html) to align with the [RHEL 6/7 toolchain ABI](https://bugzilla.redhat.com/show_bug.cgi?id=1546704).

From https://gcc.gnu.org/onlinedocs/libstdc++/manual/configure.html:
```
--disable-libstdcxx-dual-abi
Disable support for the new, C++11-conforming implementations of std::string, std::list etc. so that the library only provides definitions of types using the old ABI (see Dual ABI). This option changes the library ABI.
```

**Comment by raydouglass** [comment]
Since we no longer use system compilers, this is no longer relevant.
