### ISSUE TITLE
Other CUDA Versions (11.7)

### ISSUE THREAD

**Issue by joglekara** [rapidsai/gpuci-build-environment#280]
first, thanks for maintaining such a useful set of docker images. i have found it very useful.

i wanted to ask if I could help add images built on cuda 11.7 . I'd be happy to submit a PR if someone helps me understand what needs changing.

**Comment by raydouglass** [comment]
Hi, RAPIDS does not run builds on CUDA 11.7, so it is unsupported in this repo. However, we recently added CUDA 11.8 images.
